config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: "users#index"

  resources :users, only: [:new, :index, :create, :show] do
    resources :ideas
  end

  namespace :admin do
    resources :categories
  end



end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many :ideas

 validates :name, presence: true, uniqueness: true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :description, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ideas

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  def admin?
    role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

private

  def require_admin
    render file: "/public/404", status: 404 unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Successfully created!"
      redirect_to admin_categories_path
    else
      flash[:error] = "You need to enter a name."
      redirect_to admin_categories_path
    end
  end

  def edit
    @category = Category.find(params[:id])
    session[:category_id] = @category.id
  end

  def update
    if params[:category][:name] != ""
      Category.find(session[:category_id]).update(name: params[:category][:name])
      category = Category.find(session[:category_id])
      redirect_to admin_category_path(category)
    else
      flash[:error] = "You must enter a name!"
      redirect_to edit_admin_category_path(session[:category_id])
    end
  end

  def destroy
    category = Category.find(params[:id]).destroy
    flash[:notice] = "Deleted the category '#{category.name}'!"
    redirect_to admin_categories_path
  end

private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = current_user.ideas
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(user_added_params)
    if @idea.save
      flash[:notice] = "Idea successfully created!"
      redirect_to user_ideas_path
    else
      flash[:error] = "Creation unsuccessful. Please try again."
      redirect_to new_user_idea_path
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    if valid_idea_params
      Idea.find(params[:id]).update(user_added_params)
      idea = Idea.find(params[:id])
      redirect_to user_ideas_path(current_user)
    else
      flash[:error] = "You must enter a name and a description!"
      redirect_to edit_user_idea_path(current_user, params[:user_id])
    end
  end

  def destroy
    Idea.find(params[:id]).delete
    redirect_to user_ideas_path(current_user)
  end

  private

    def idea_params
      params.require(:idea).permit(:name, :description, :category_id)
    end

    def user_added_params
      full_params = idea_params
      full_params[:user_id] = current_user.id
      full_params
    end

    def valid_idea_params
      (params[:idea][:name] && params[:idea][:description]) != ""
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_ideas_path(@user)
    elsif @user && !@user.authenticate(params[:session][:password])
      flash[:error] = "Incorrect password, please try again."
      redirect_to login_path
    else
      flash[:error] = "Account not registered. Please create an account"
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to new_user_path
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_ideas_path(@user)
    else
      flash[:error] = "Invalid login, please try again."
      redirect_to new_user_path
    end
  end

private

    def user_params
      params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/edit.html.erb
<h3>Please edit the category</h3>

  <%= form_for @category, url: admin_category_path, method: :patch do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, value: @category.name %>
    <%= f.submit "Submit" %>
  <% end %>

app/views/admin/categories/index.html.erb
<div class="row">
  <div>
    <h3 align="center">All Categories</h3>
  </div>
</div>

<div class="row">

  <div class="col-md-3">

  </div>

  <table class="col-md-6 well table-hover table-bordered" id="categories">
    <tr>
      <th>Category</th>
      <th></th>
      <th></th>
    </tr>
    <% @categories.each do |category| %>
    <tr id="category_<%= category.id.to_s %>">
      <td><%= category.name %> </td>
      <td align="center"><%= link_to "Edit", edit_admin_category_path(category) %></td>
      <td align="center"><%= link_to "Delete", admin_category_path(category), method: :delete %></td>
    </tr>
    <% end %>
  </table>

</div>

app/views/admin/categories/new.html.erb
<h3>Please create a category</h3>

  <%= form_for @category, url: admin_categories_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
  <% end %>

app/views/admin/categories/show.html.erb
<h3>Check out your category!</h3>

<div class="" id="category">
  <p>
    Name: <%= @category.name %>
  </p>
</div>

app/views/ideas/edit.html.erb
<h3>Edit your idea</h3>

<div id="edit_idea_form">
  <%= form_for(@idea, url: user_idea_path(current_user, @idea), method: :patch) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/ideas/index.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div align="center" class="col-md-6" id="create_idea">
    <div class="btn btn-default"><%= link_to "Create an idea", new_user_idea_path(current_user) %></div>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
  </div>
  <div align="center" class="col-md-6">

  </div>
</div>

<div class="row">
  <h3 align="center">Your Ideas</h3>
</div>
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6" id="ideas">
    <table class="table table-bordered table-hover">
      <tr>
        <th>Name</th>
        <th>Description</th>
      </tr>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td class="btn btn-default"><%= link_to "Edit", edit_user_idea_path(current_user, idea) %></td>
        <td class="btn btn-default"><%= link_to "Delete", user_idea_path(current_user, idea), method:  :delete %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/ideas/new.html.erb
<h3>Create a new idea</h3>

<div class="">
  <%= form_for(@idea, url: user_ideas_path(current_user)) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.submit "Create" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="/application.css">
</head>
<body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">Idea Box</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <span style="float: right" class="navbar-text">
            <% if current_admin? %>
              Logged in as <strong><%= 'admin ' if current_admin? %></strong><%= current_user.username %> |
              <%= link_to "Logout", logout_path, method: :delete %>
            <% elsif current_user %>
              Logged in as <%= current_user.username %> |
              <%= link_to "Logout", logout_path, method: :delete %>
            <% else %>
              <%= link_to "Login", login_path %> |
              <%= link_to "Sign Up", new_user_path %>
            <% end %>
          </span>
        </div>
      </div>
    </nav>
  <div class="row panel">
    <div class="col-md-4">
    <% flash.each do |name, message| %>
      <%= content_tag :div, message %>
    <% end %>
    </div>
      <% if current_admin? %>
    <div class="col-md-4">
        <%= link_to "View Categories", admin_categories_path %>
    </div>
    <div class="col-md-4">
      <%= link_to "Create A Category", new_admin_category_path %>
    </div>
    <% end %>
  </div>
<%= yield %>

<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/new.html.erb
<div class="row">

  <div class="col-md-3">

  </div>
  <div class="col-md-6">
    <h3 align="center">Please Create An Account</h3>

    <table align="center">
      <%= form_for(@user) do |f| %>
      <tr>
        <td><%= f.label :username %></td>
        <td><%= f.text_field :username %></td>
      </tr>
      <tr>
        <td><%= f.label :password %></td>
        <td><%= f.password_field :password %></td>
      </tr>
      <tr>
        <td><%= f.submit "Create Account"%></td>
      </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/users/show.html.erb
<h1>User Page</h1>

<p>
  Logged in as <%= @user.username %>
</p>